import type { Metadata } from "next";
import "../globals.css";
import StoreProvider from "../StoreProvider";


export const metadata: Metadata = {
  title: "HEHEHE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <h1 className="text-xl font-bold text-center mb-4"> hhohoho</h1>
        <StoreProvider >
            {children}
        </StoreProvider>
      </body>
    </html>
  );
}
